var N = null;var sourcesIndex = {};
sourcesIndex["bitflags"] = {"name":"","files":["lib.rs"]};
sourcesIndex["ferroboy"] = {"name":"","dirs":[{"name":"assembly","files":["disassemble.rs","instruction.rs","instruction_stream.rs","mod.rs"]},{"name":"operations","dirs":[{"name":"add","files":["mod.rs","narrow.rs","wide.rs"]},{"name":"dec","files":["mod.rs","narrow.rs","wide.rs"]},{"name":"inc","files":["mod.rs","narrow.rs","wide.rs"]},{"name":"jump","files":["mod.rs","position.rs","relative.rs"]},{"name":"load","files":["mod.rs","narrow.rs","wide.rs"]},{"name":"rotate","files":["left_carry.rs","mod.rs","right_carry.rs"]}],"files":["and.rs","halt.rs","interrupts.rs","mod.rs","nop.rs","operation.rs","pop.rs","push.rs","stop.rs","sub.rs"]},{"name":"system","dirs":[{"name":"register","files":["mod.rs","narrow.rs","wide.rs"]}],"files":["alu.rs","cartridge.rs","config.rs","cpu.rs","mmu.rs","mod.rs","opcodes.rs"]}],"files":["helpers.rs","lib.rs","state.rs"]};
sourcesIndex["ferroboy_core"] = {"name":"","files":["ferroboy_core.rs","lib.rs"]};
sourcesIndex["ferroboy_dasm"] = {"name":"","files":["main.rs"]};
sourcesIndex["lazy_static"] = {"name":"","files":["inline_lazy.rs","lib.rs"]};
sourcesIndex["libc"] = {"name":"","dirs":[{"name":"unix","dirs":[{"name":"linux_like","dirs":[{"name":"linux","dirs":[{"name":"gnu","dirs":[{"name":"b64","dirs":[{"name":"x86_64","files":["align.rs","mod.rs","not_x32.rs"]}],"files":["mod.rs"]}],"files":["align.rs","mod.rs"]}],"files":["align.rs","mod.rs"]}],"files":["mod.rs"]}],"files":["align.rs","mod.rs"]}],"files":["fixed_width_ints.rs","lib.rs","macros.rs"]};
sourcesIndex["libretro_backend"] = {"name":"","files":["lib.rs"]};
sourcesIndex["libretro_sys"] = {"name":"","files":["lib.rs"]};
sourcesIndex["once_cell"] = {"name":"","files":["imp_std.rs","lib.rs"]};
sourcesIndex["pico_args"] = {"name":"","files":["lib.rs"]};
createSourceSidebar();
