[package]
name = "ferroboy"
version = "0.1.0"
authors = ["berwyn <berwyn.codeweaver@gmail.com>"]
edition = "2018"

[dependencies]
arrayvec = { version = "0.4.11", features = ["std", "array-sizes-33-128", "array-sizes-129-255"] }
bitflags = "1.1.0"
