[package]
name = "ferroboy"
version = "0.1.0"
authors = ["berwyn <berwyn.codeweaver@gmail.com>"]
edition = "2018"

[dependencies]
arrayvec = { version = "0.5.1", features = ["std", "array-sizes-33-128", "array-sizes-129-255"] }
bitflags = "1.2.1"
once_cell = "1.4.0"

[dev-dependencies]
pico-args = "0.3.3"
