[package]
name = "ferroboy-dasm"
version = "0.1.0"
authors = ["berwyn <berwyn.codeweaver@gmail.com>"]
edition = "2018"

[dependencies]
eyre = "0.6.5"
jane-eyre = "0.3.0"
ferroboy = { path = "../ferroboy" }
pico-args = "0.3.4"
