[package]
name = "ferroboy-core"
version = "0.1.0"
authors = ["berwyn <berwyn.codeweaver@gmail.com>"]
edition = "2021"
rust-version = "1.56"

[lib]
crate-type = ["cdylib"]

[dependencies]
ferroboy = { path = "../ferroboy" }
lazy_static = "1.4.0"
libretro-backend = "0.2.1"
