name: Rust

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    strategy:
      matrix:
        rust: [stable, beta]

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.rust == 'beta' }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup up a Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: beta
          components: clippy, rustfmt
          default: true
      - name: Setup X11
        # Required to build Druid
        run: |
          sudo apt-get update
          sudo apt-get install -yqq \
            libx11-dev \
            libgtk-3-dev
      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
      - name: clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --all-targets

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, beta]

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.rust == 'beta' }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Set up a Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          default: true
      - name: Setup X11
        if: contains(matrix.os, 'ubuntu')
        # Required to build Druid
        run: |
          sudo apt-get update
          sudo apt-get install -yqq \
            libx11-dev \
            libgtk-3-dev
      - name: Run Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --all-targets

  build:
    needs: test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, beta]

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.rust == 'beta' }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Set up a Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy, rustfmt
          default: true
      - name: Setup X11
        if: contains(matrix.os, 'ubuntu')
        # Required to build Druid
        run: |
          sudo apt-get update
          sudo apt-get install -yqq \
            libx11-dev \
            libgtk-3-dev
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets --verbose --release
