name: Rust

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, beta]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up a Rust toolchain
        uses: hecrj/setup-rust-action@v1.3.1
        with:
          rust-version: ${{ matrix.rust }}
          components: clippy,rustfmt
      - uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Lint
        run: cargo clippy --all-features --all-targets -- -D warnings
      - name: Format
        run: cargo fmt -- --check
      - name: Build
        run: cargo build --all-targets --verbose
      - name: Test
        run: cargo test --verbose
