name: Rust

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, beta]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Set up a Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy, rustfmt
          default: true
      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
      - name: Lint
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --all-targets
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose
        if: ${{ matrix.os != 'ubuntu-latest' }}
      - name: Test
        uses: actions-rs/tarpaulin@v0.1.0
        with:
          version: "0.12.4"
          args: "-- --test-threads 1"
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - name: Upload to Coveralls
        uses: coverallsapp/github-action@v1.1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets --verbose --release
